name: tiger
channels:
  - pytorch
  - defaults
  - anaconda
dependencies:
  - python=3.9
  - cudatoolkit
  - pip
  - pytorch=1.12.1
  - pytorch-mutex=1.0=cuda
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - pip:
    - accelerate==0.23.0
    - diffusers==0.18.0
    - gradio==3.47.1
    - gradio-client==0.6.0
    - huggingface-hub==0.15.1
    - omegaconf==2.3.0
    - sentencepiece==0.1.97
    - transformers==4.34.0
